"""
Memory data models and schemas for CHAI.
Supports Level A (short-term chat history), Level B (long-term user memory),
and Level C (user profile & preferences).
"""
from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional, Dict, Any, Literal
import uuid
from pydantic import BaseModel, Field


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class MemoryCategory(str, Enum):
    EDUCATION = "education"
    CAREER_GOAL = "career_goal"
    PROJECT = "project"
    PREFERENCE = "preference"
    EXPERTISE = "expertise"
    CONSTRAINT = "constraint"
    GENERAL = "general"


class MemoryItem(BaseModel):
    """
    A single durable, long-term memory entry for a specific user.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str
    memory: str
    category: MemoryCategory = MemoryCategory.GENERAL
    importance: int = Field(default=3, ge=1, le=5, description="Importance score (1 to 5)")
    created_at: str = Field(default_factory=_utc_now_iso)
    updated_at: str = Field(default_factory=_utc_now_iso)


class UserProfile(BaseModel):
    """
    Structured profile and durable preferences for an authenticated user.
    """
    user_id: str
    name: Optional[str] = None
    email: Optional[str] = None
    role: Optional[str] = None
    goals: List[str] = Field(default_factory=list)
    interests: List[str] = Field(default_factory=list)
    preferences: Dict[str, Any] = Field(default_factory=dict)
    updated_at: str = Field(default_factory=_utc_now_iso)


class ChatMessageRecord(BaseModel):
    """
    A single message in short-term conversation memory.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    conversation_id: str
    user_id: str
    role: Literal["user", "assistant", "system"]
    content: str
    created_at: str = Field(default_factory=_utc_now_iso)


class ConversationRecord(BaseModel):
    """
    Metadata for a conversation thread.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str
    title: str = "New Conversation"
    created_at: str = Field(default_factory=_utc_now_iso)
    updated_at: str = Field(default_factory=_utc_now_iso)


class ContextPayload(BaseModel):
    """
    Unified context generated by ContextManager.
    """
    user_id: str
    conversation_id: Optional[str] = None
    user_profile: Optional[UserProfile] = None
    recent_messages: List[ChatMessageRecord] = Field(default_factory=list)
    relevant_memories: List[MemoryItem] = Field(default_factory=list)
    formatted_context_string: str = ""
